USE TURISMOPERU_JLLB
go

--PERMISOS VENDEDOR
GRANT SELECT, INSERT
ON JLLB.CLIENTE
TO ROL_VENDEDOR;

GRANT SELECT, INSERT
ON JLLB.RESERVA
TO ROL_VENDEDOR;
GO

GRANT SELECT
ON JLLB.ALOJAMIENTO
TO ROL_VENDEDOR;
GO

GRANT SELECT
ON JLLB.HABITACION
TO ROL_VENDEDOR;
GO

DENY DELETE
ON JLLB.CLIENTE
TO ROL_VENDEDOR;
GO

DENY DELETE
ON JLLB.RESERVA
TO ROL_VENDEDOR;
GO

--PERMISOS ANALISTA
GRANT SELECT ON JLLB.RESERVA TO ROL_ANALISTA;
GO
GRANT SELECT ON JLLB.PAGO TO ROL_ANALISTA;
GO
GRANT SELECT ON JLLB.ALOJAMIENTO TO ROL_ANALISTA;
GO
GRANT SELECT ON JLLB.HABITACION TO ROL_ANALISTA;
GO
GRANT SELECT ON JLLB.PAQUETE TO ROL_ANALISTA;
GO
GRANT SELECT ON JLLB.LUGAR_TURISTICO TO ROL_ANALISTA;
GO
--NO HABILITADO
DENY INSERT, UPDATE, DELETE ON JLLB.RESERVA TO ROL_ANALISTA;
GO
DENY INSERT, UPDATE, DELETE ON JLLB.PAGO TO ROL_ANALISTA;
GO
DENY INSERT, UPDATE, DELETE ON JLLB.ALOJAMIENTO TO ROL_ANALISTA;
GO
DENY INSERT, UPDATE, DELETE ON JLLB.HABITACION TO ROL_ANALISTA;
GO
DENY INSERT, UPDATE, DELETE ON JLLB.PAQUETE TO ROL_ANALISTA;
GO
GRANT SELECT ON JLLB.LUGAR_TURISTICO TO ROL_ANALISTA;
GO

--Asignar ROL
ALTER ROLE rol_vendedor add member
jllb_vendedor;

ALTER ROLE rol_vendedor add member
jllb_vendedor;